### ISSUE TITLE
Auto-complete control

### ISSUE THREAD

**Issue by icecandy** [appcelerator/atom-appcelerator-titanium#105]
Is it possible to turn off auto-complete using this Atom package?
Ideally I would like to use it with a key combination when I need it (eg Ctrl + space), rather than it auto-popping up, which in general is rather annoying.

**Comment by ewanharris** [comment]
Hey @icecandy, not sure if you've solved this. We use [autocomplete-plus](https://github.com/atom/autocomplete-plus) to handle the autocomplete in this package. 

In the settings for that package you can disable the "Show suggestions on keystroke" option to allow you to use key-mapping you chose for `autocomplete-plus:activate` (defaults to ctrl-space)

**Comment by icecandy** [comment]
@ewanharris  I did manage to find the settings in Atom to turn off auto-complete so that it only show if I use Ctrl + space.

**Comment by ewanharris** [comment]
Grand! Thanks for getting back, I'll close this issue out.
