### ISSUE TITLE
Error fetching environment information

### ISSUE THREAD

**Issue by DouglasHennrich** [appcelerator/atom-appcelerator-titanium#107]
`Ensure you have installed Appcelerator CLI tools. You may need to set the full path to the appc command in package settings.`

1. Open Atom

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.4
**Thrown From**: [appcelerator-titanium](https://github.com/appcelerator/atom-appcelerator-titanium) package 1.1.1

### Non-Core Packages

```
appcelerator-titanium 1.1.1 
atom-ide-ui 0.12.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
busy-signal 1.4.3 
color-picker 2.3.0 
dash-syntax 0.4.1 
dash-ui 0.4.4 
default-language 0.3.1 
file-icons 2.1.21 
fold-functions 0.5.0 
highlight-selected 0.13.1 
hyperclick 0.1.5 
intentions 1.1.5 
jsonlint 1.1.4 
language-babel 2.85.0 
language-vue 0.23.1 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
pigments 0.40.2 
pretty-json 2.0.1 
scroll-through-time 0.3.0 
titanium-alloy 0.14.6 
todo-show 2.3.0 
```

<img width="853" alt="captura de tela 2018-06-13 as 15 59 39" src="https://user-images.githubusercontent.com/10107024/41372154-d68743ce-6f22-11e8-9b5f-32aee10c66f7.png">

**Comment by DouglasHennrich** [comment]
I also already tried to open Atom through terminal

**Comment by hansemannn** [comment]
Try:
```bash
hknoechel$ which appc
/usr/local/bin/appc
```

**Comment by DouglasHennrich** [comment]
I solve my problem doing a long setTimeout on function that fetch `appc info -o json` since I had alot of simulators, it took my time to retrieve it
