### ISSUE TITLE
Liveview  :improvement:

### ISSUE THREAD

**Issue by draggmen** [appcelerator/atom-appcelerator-titanium#108]
Live view check or selector. Can you implement a check or selector to add another parameter on run with live view  '--liveview','true'. For now I add this parameters on source code on app.js
.....
let args = {};
		if (buildCommand === 'run') {
			args = [
				'--platform', platform,
				'--target', targetType,
				'--log-level', logLevel,
				'--liveview','true'
			];
.....
thanks

**Comment by hansemannn** [comment]
Please feel free to submit a pull request for this, so everyone can benefit from it :-).
