### ISSUE TITLE
Autosave custom args

### ISSUE THREAD

**Issue by developer82** [appcelerator/atom-appcelerator-titanium#114]
When running with custom arguments, it's usually the way developers run their project each and every time. And every time Atom is being restarted there's a need to re-enter the same arguments.

Have the option (inside the package settings - should be true by default) to auto save the last ran "Custom args" that was were put in the text box and loaded when the custom args appears automatically.

**Comment by hansemannn** [comment]
It should be quite easy when pulling in [electron-store](https://github.com/sindresorhus/electron-store). We also persist some other data already (like keystores for Android I think), so you could try and hack it in! 😙

**Comment by hansemannn** [comment]
Added via #111, works fine!
