### ISSUE TITLE
Improve autocomple of version in tiapp

### ISSUE THREAD

**Issue by m1ga** [appcelerator/atom-appcelerator-titanium#119]
When setting a new version in tiapp.xml it will present you a drop down with all available version but it won't overwrite the numbers you've already typed

**Problem:**
* select all text between `<sdk-version>7.2.0.GA</sdk-version>`
* start typing 7.
* select a SDK
* it will result in `<sdk-version>7.7.2.0.GA<sdk-version>`

It should replace the whole text between the tags when you selected a version

[Video of the problem](https://migaweb.de/ti_atom_version.mp4)

**Comment by hansemannn** [comment]
Fixed via #121
