### ISSUE TITLE
Simulator option not available in Run mode

### ISSUE THREAD

**Issue by prashantsaini1** [appcelerator/atom-appcelerator-titanium#120]
Just started Atom afresh and couldn't see any iOS simulators. Everything is fine in my system as all simulators were there till y'day and Appc Studio is also showing the simulators properly and I can also run the iOS app via terminal but Atom cannot find them at all after multiple relaunch and even Enable/Disable the package.
![screen shot 2018-08-08 at 8 13 08 am](https://user-images.githubusercontent.com/20779626/43813427-4c0ee728-9ae3-11e8-9bf1-6cc1fbd5b27b.png)

**Comment by hansemannn** [comment]
Interesting. Does this happen with new projects as well? You may want to check your appc version `appc -v` and reinstall the plugin - just some troubleshooting.

**Comment by prashantsaini1** [comment]
Yes, I tried everything even reinstalling Atom and its Appc package. But when after a single launch of iOS simulator from terminal, even Appc Studio is not able to launch them. It shows the famous **Invalid Device** error.

Studio is showing the list of simulators in popup, but this command `appc ti info -t ios` is not showing any simulators on terminal. Here are the logs of this command:

```
Appcelerator Command-Line Interface, version 7.0.4
Copyright (c) 2014-2018, Appcelerator, Inc.  All Rights Reserved.

Xcode
  9.0 (build 9A235)
    Install Location          = /Applications/Xcode.app/Contents/Developer
    iOS SDKs                  = 11.0
    iOS Simulators            = 11.0
    Watch SDKs                = none
    Watch Simulators          = none
    Supported by TiSDK 7.2.0.GA = yes
    EULA Accepted             = yes
    Teams                     = none
 
iOS Keychains
  login.keychain-db           = /Users/prashant/Library/Keychains/login.keychain-db
  System.keychain             = /Library/Keychains/System.keychain


Apple WWDR Certificate
  Apple WWDR                  = installed
 
iOS Simulators
  None

WatchOS Simulators
  None

Connected iOS Devices
  None

Issues
  No issues detected! Your development environment should be working perfectly!
```

The only solution I can try is just reinstalling everything from scratch, like Node, NPM, Atom, Studio, Xcode. Would be great if I can get a solution as I sure that something has just broken up when I start the MacBook this morning.

Note: I can still run on Android from Studio but not from Atom-Appc Package. It shows **Failed to run dexer** error.

**Comment by hansemannn** [comment]
It may be a known issue with Xcode 9.4.1 (https://jira.appcelerator.org/browse/DAEMON-259), which is fixed in SDK 7.3.0 / 7.0.5. The GA is expected for this week, so this hopefully helps.

**Comment by hansemannn** [comment]
Altough it's working fine for me, using 7.2.0.

**Comment by prashantsaini1** [comment]
I am also using Ti 7.2.0.GA and everything was working just fine till last night. Can you send me the logs of your system installation setup so I can match it with mine?

**Comment by prashantsaini1** [comment]
This command worked to setup the Xcode path manually `sudo xcode-select -switch /Applications/Xcode.app/`.

Closing this bug now as it worked after I ran the above command on terminal.
