### ISSUE TITLE
LiveView not working after using SDK 7.3.0.GA and CLI 7.0.5

### ISSUE THREAD

**Issue by prashantsaini1** [appcelerator/atom-appcelerator-titanium#122]
After I updated Studio, SDK and CLI to latest few hours back, Atom package is not running the app in LiveView mode. However it shows that it's using the LiveView command in console, but the app is not launching in liveview mode.

Note: Studio is able to run it properly.
![screen shot 2018-08-20 at 10 05 28 am](https://user-images.githubusercontent.com/20779626/44322289-47081200-a46a-11e8-9f01-a025a192c94a.png)

**Comment by hansemannn** [comment]
For me personally, I use the standalone version of liveview (`npm i -g liveview`). After installing, you should reference the hook from there instead of Studio, inside the `paths` section of the `~/.titanium/config.json`:
```json
	"paths": {
		"commands": [],
		"hooks": [
			"/Users/hknoechel/Documents/dev/liveview/hook"
		],
		"modules": [],
		"plugins": [],
		"sdks": [
			"/Users/hknoechel/Library/Application Support/Titanium"
		],
		"templates": []
	},
```

**Comment by hansemannn** [comment]
Looks like it's not an issue anymore, closing for now.

**Comment by e3bmo3ty** [comment]
> For me personally, I use the standalone version of liveview (`npm i -g liveview`). After installing, you should reference the hook from there instead of Studio, inside the `paths` section of the `~/.titanium/config.json`:
> 
> ```json
> 	"paths": {
> 		"commands": [],
> 		"hooks": [
> 			"/Users/hknoechel/Documents/dev/liveview/hook"
> 		],
> 		"modules": [],
> 		"plugins": [],
> 		"sdks": [
> 			"/Users/hknoechel/Library/Application Support/Titanium"
> 		],
> 		"templates": []
> 	},
> ```

thanks so much....that was very helpful +1
