### ISSUE TITLE
Refresh devices not working on iOS

### ISSUE THREAD

**Issue by m1ga** [appcelerator/atom-appcelerator-titanium#127]
### Describe the Bug
When attaching a iPhone/iPad to an existing Atom session and clicking the "Refresh devices" button it won't recognise them. Android devices are shown correctly.

### Steps to reproduce the Bug
Steps to reproduce the behavior, e.g.:
1. open atom
2. open appc project
3. attach iOS device
4. click "refresh devices"

### Expected Behavior
Device to compile to should appear in the list

### Your Environment
| Software | Version |
| ---------------- | ---------- |
| Titanium SDK | 7.3.1 |
| CLI | 7.0.6 |
| Atom | 1.30.0 |
| Titanium Atom Package |1.4.0 |

**Comment by ewanharris** [comment]
@m1ga Are you still seeing this issue? I'm not able to reproduce it locally

**Comment by m1ga** [comment]
No, with the latest 1.4.2 and Atom 1.32.1 it's working fine again. Attaching the iPad and it's found in the "iOS device" list after refreshing
