### ISSUE TITLE
JDK (Java Development Kit) not found on windows

### ISSUE THREAD

**Issue by sorin360** [appcelerator/atom-appcelerator-titanium#129]
[ERROR] JDK (Java Development Kit) not found.
[ERROR] If you already have installed the JDK, verify your JAVA_HOME environment variable is correctly set.
[ERROR] The JDK can be downloaded and installed from http://appcelerator.com/jdk.
Build failed. Process exited with code 1.

**Comment by ewanharris** [comment]
Hey @sorin360, thanks for the report, but we need a little more info to help with your issue.

Titanium requires a JDK to be installed, do you have one? If not please download and install [JDK 10](https://www.oracle.com/technetwork/java/javase/downloads/jdk10-downloads-4416644.html. If you do, please make sure the JAVA_HOME is set correctly, if you let me know what OS you are using I can help tell you what the path should look like.

**Comment by ewanharris** [comment]
Apologies @sorin360, I somehow managed to miss you saying Windows in the title! You JAVA_HOME env var should look something like `C:\Program Files\Java\jdk1.8.0_181`

**Comment by ewanharris** [comment]
@sorin360, any updates here? Did you manage to get it working?

**Comment by ewanharris** [comment]
Closing as no feedback was received.
