### ISSUE TITLE
Uncaught Error: NOTICE: Longjohn is known to cause CPU usage due to its extensive data collection...

### ISSUE THREAD

**Issue by mybikewasstoleninside** [appcelerator/atom-appcelerator-titanium#137]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [appcelerator-titanium](https://github.com/appcelerator/atom-appcelerator-titanium) package 1.5.1

### Stack Trace

Uncaught Error: NOTICE: Longjohn is known to cause CPU usage due to its extensive data collection during runtime.
It generally should not be used in production applications.

```
At events.js:183

Error: NOTICE: Longjohn is known to cause CPU usage due to its extensive data collection during runtime.
It generally should not be used in production applications.

    at /packages/appcelerator-titanium/node_modules/suppose/lib/suppose-process.js:93:26)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

### Commands

```
     -7:38.2.0 titanium-build:run-android-devices (input.hidden-input)
     -7:32 appc:new (ul.list-inline.tab-bar.inset-panel)
     -5:46.4.0 application:open-folder (div.package-detail.panels-item)
     -4:29.6.0 appc:new (div.package-detail.panels-item)
```

### Non-Core Packages

```
appcelerator-titanium 1.5.1 
atom-ide-ui 0.13.0 
build 0.70.0 
busy-signal 2.0.0 
react-snippets 1.1.2 
script 3.18.1 
titanium-build 0.8.1 
```

**Comment by ewanharris** [comment]
Thanks for the report @mybikewasstoleninside, I don't believe this to be an issue with this package, the SDK uses longjohn to provide improved stacktraces. From a quick investigation it looks like that package outputs this warning if `process.env.NODE_ENV === 'production'`, which I believe is being set by Atom itself, I'll take a look into whether we can filter that out before spawning processes

**Comment by ewanharris** [comment]
longjohn was removed from the CLI
