### ISSUE TITLE
Colors hints in TSS

### ISSUE THREAD

**Issue by Frk7** [appcelerator/atom-appcelerator-titanium#139]
### Summary
Question about hints for properties about colors (ex. backgroundColor) in TSS.
When you add this kind of properties you get hints about colors, but when you type any character all the hints always disappear. Is this expected?

### Your Environment
| Software | Version |
| macOS | 10.14.2 |
| Titanium SDK | | 7.5.0
| CLI | | 7.0.7
| Atom | | 1.34.0
| Titanium Atom Package | | 1.5.1

**Comment by m1ga** [comment]
You can press Ctrl + Space after the `:` or inside the `" "` to get the autocompletion for e.g. the colors again

**Comment by Frk7** [comment]
> You can press Ctrl + Space after the `:` or inside the `" "` to get the autocompletion for e.g. the colors again

It's not working for me. After the `:` i have the autocompletion, then i an write `'` and the autocompletion is still there, if I write `w` for having `white` the autocompletion disappears.
It would also be nice that I can type directly `w` after `:` to have `white` suggested.

**Comment by m1ga** [comment]
ah ok. I wasn't checking the selection of the colors. I can confirm, that I can't type `w` to select `white` and when there is one character inside the `"` it is not opening. For other elements like `textAlign` and e.g. `Ti.UI.TEXT_ALIGNMENT_CENTER` you can type `CENT` to select the center option. A `.` will stop the selection, too. Not sure how to fix that (if it is inside the package or inside the autocomplete package) but it looks like it is not working correctly inside strings

**Comment by Frk7** [comment]
If typing `Ti.UI.` could narrow the suggestions to that namespace, it would be wonderful.

**Comment by ewanharris** [comment]
This looks to be a bug in the autocomplete provider, it should be using the provided text to filter the colours but isn't.

**Comment by Frk7** [comment]
Small feature request to autocompletion for `color: b`: now selecting for example "black" suggestion it autocompletes in `color: black` it would be nice instead `color: 'black'`.
