### ISSUE TITLE
TSS id rules directly in controller's TSS after ctrl+click

### ISSUE THREAD

**Issue by Frk7** [appcelerator/atom-appcelerator-titanium#141]
### Summary
When you ctrl+click on some id in XML, you can choose to create the TSS rule in controller's TSS or in app.tss.
For a TSS class it's ok, but id rules ~95% (100%?) of the times belong to controller's TSS.
~~So imho 95-100% of the times i'm doubling the clicks needed for a simple action.
Imho id rules have to go directly in controller's TSS after ctrl+click.~~ (Incorrect assumption)

**Comment by Frk7** [comment]
Another point of view is to ask for a confirmation, in this case it would be ok to leave things as they are.

**Comment by ewanharris** [comment]
This seems a sensible request to me, if you're styling by id it seems sensible for us to guide people into doing that at the views tss level rather than the apps tss level

**Comment by Frk7** [comment]
> This seems a sensible request to me, if you're styling by id it seems sensible for us to guide people into doing that at the views tss level rather than the apps tss level

Ok, however the part where i say:
> ...So imho ~95-100% of the times i'm doubling the clicks needed for a simple action.
> Imho id rules have to go directly in controller's TSS after ctrl+click.
is incorrect beacause it's not certain that 100% of the times the user wants to create the id rule, for example sometimes I use _Ctrl+click_ only to check if the rule is present but I don't want to create it.

**Comment by ewanharris** [comment]
@Frk7, I took a brief look at this today, from what I saw even when we only suggest one possible path (the corresponding tss file), atom will still show the dialog, which seems ok to me based off your update?

**Comment by Frk7** [comment]
> @Frk7, I took a brief look at this today, from what I saw even when we only suggest one possible path (the corresponding tss file), atom will still show the dialog, which seems ok to me based off your update?

Yes, it's ok 👍
