### ISSUE TITLE
Incorrect autocomplete suggestions order in TSS

### ISSUE THREAD

**Issue by Frk7** [appcelerator/atom-appcelerator-titanium#143]
### Describe the Bug
Autocomplete suggestions order in TSS files is incorrect for some properties (e.g. color, bottom).

![autocompletion](https://user-images.githubusercontent.com/6583871/53964234-3611ac00-40ef-11e9-8ec0-1349cfa6a7b3.png)

### Steps to reproduce the Bug
1. Open a TSS file
2. Start typing a property like `color` or `bottom` inside a TSS rule
3. Suggestions order is incorrect

### Expected Behavior
After typing `colo` the first suggestion has to be `color`.

### Your Environment
| macOS | 10.14.3 |
| Titanium SDK | 7.5.0 |
| CLI | 7.0.9 |
| Atom | 1.34.0 |
| Titanium Atom Package | 1.5.1 |

**Comment by ewanharris** [comment]
This will be down to the way we sort completions, right now we just do an alphabetical sort. We should do scoring on the similarity of the string to the text to improve that we then sort by.

**Comment by Frk7** [comment]
I think there isn't only an alphabetical sort.

![co](https://user-images.githubusercontent.com/6583871/54625174-0eb3cb00-4a6f-11e9-841b-fa0afa14e6da.png)

The suggestions in this image are what expected starting from `code` and not in alphabetical order, the others before are incorrect in that positions.

Using [yomybaby/atom-titanium plugin](https://github.com/yomybaby/atom-titanium) the suggestions are right (don't know where that 'comebak' came from 😅)
![co2](https://user-images.githubusercontent.com/6583871/54626105-d1503d00-4a70-11e9-8257-02d7c2396754.png)

**Comment by m1ga** [comment]
The property values filter better now (1.6.0), the properties itself are not weighted correctly (e.g. it should score the beginning of a word higher, like the `color` example is shown above).
