### ISSUE TITLE
Add quick clean button to toolbar

### ISSUE THREAD

**Issue by developer82** [appcelerator/atom-appcelerator-titanium#161]
Add a button to the toolbar that clicking it would run in the terminal the clean command for the project

**Comment by m1ga** [comment]
Was there already: https://github.com/appcelerator/atom-appcelerator-titanium/pull/93 but we moved it to the menu/keyboard shortcut

**Comment by developer82** [comment]
Why should it remain as only menu/keyboard shortcut? It takes more clicks to get to it than pointing the mouse to the correct icon, and toolbar has space to spare. I generally think more useful items could be added to the toolbar as well.

**Comment by m1ga** [comment]
maybe because you shouldn't clean your project and the CLI should do it when needed (like removing background apps from ios :smile: ). I don't know the exact reason but to get it merged in the first place I was asked to remove the icon

**Comment by developer82** [comment]
I happen to clean my project every once in a while, and I find it as good practice. Especially when working with assets. The CLI doesn't clean it all up I think.
And if what you're describing is the case then this should not even be presented as a shortcut at all, or as a CLI command if we're at it ;).
But as long as it's there I think the toolbar should make the developer's job more accessible (and as mentioned above with even more shortcuts to useful commands).

**Comment by m1ga** [comment]
the toolbar is very empty so I'm all for adding more features there (thats why I made the PR :-) ). I just tried to think why they didn't want it to be there. Maybe it is a "2nd level" command and having it next to build suggests you need it that often. 

But again: not up to me to decide, just wanted to say that it was rejected before ;-)

BTW: I only use it when I zip my projects.

**Comment by developer82** [comment]
Let's give it a shot. I've opened some more feature requests about the toolbar (I want to try to develop them as a small challenge since this is my first one developing for the Atom editor).
BTW, I'm using a customized side toolbar where I've added my self useful shortcuts, including some Titanium ones since the Ti Toolbar didn't have them.
