### ISSUE TITLE
Unable to select correct distribution certificate if duplicate names exist

### ISSUE THREAD

**Issue by MarkBoyer** [appcelerator/atom-appcelerator-titanium#183]
If more than one distribution certificate exists with the same name but different expiration dates (different UUIDs), only the first expiring certificate can be selected from the certificate dropdown when performing a distribution build.

Steps to reproduce the behavior, e.g.:
1. From the action dropdown, select Ad-Hoc (or App Store)
2. Click on the "Signing Settings" icon
3. Only the first expiring certificate with the duplicate name can be selected

Expected Behavior
Be able to distinguish duplicate named certificates based on expiration date or UUID.  Enable the correct associated provisioning profiles for the selected certificate.

Environment
| Software              | Version    |
| --------------------- | ---------- |
| Titanium SDK          | 8.2.0.GA   |
| CLI                   | 7.1.1      |
| Atom                  | 1.40.1     |
| Titanium Atom Package | 1.9.1      |

Work around is to build using command line.  In VS-Code plugin, certificates are both selectable.

<img width="891" alt="Screen Shot 2019-10-02 at 12 34 33 PM" src="https://user-images.githubusercontent.com/3966735/66076703-394d0900-e513-11e9-9669-bdc24f0146a6.png">

<img width="1523" alt="Screen Shot 2019-10-02 at 12 34 59 PM" src="https://user-images.githubusercontent.com/3966735/66076702-394d0900-e513-11e9-87f2-796c13b98e76.png">

**Comment by ewanharris** [comment]
@MarkBoyer, I think we're partially limited here by the CLI. If you have two valid certificates with an identical name then the CLI has no real way to tell them apart from the command line option value (the only unique thing available is the pem and I don't think we want to accept that as a value).

So in this case where both the certs are `iPhone Distribution: Joe Bloggs`, the CLI will ultimately end up prompting for which one is wanted (which Atom can't handle).

Ultimately though, there is a bug here though in that you can only select the first one and we need to work on supporting the generic Apple certs here too so we will be fixing those issues.
