### ISSUE TITLE
Improvement: Add `ti` command

### ISSUE THREAD

**Issue by m1ga** [appcelerator/atom-appcelerator-titanium#187]
The current package only supports `appc` commands (e.g. `appc run`). It is not possible to switch to a `ti build` version.

It should be possible to add a switch to switch to `ti` commands or even a way to detect if it is not a registered app and switch automatically to normal `ti` commands.

**Comment by ewanharris** [comment]
@m1ga, this is something we've discussed doing before but it got put to one side as it wasn't a priority. In the VS Code extension we had an easy structure for how we could offer this per-project by allowing `.vscode/settings.json` to configure it, this would then be respected across all machines used.

I don't believe Atom supports a project config like that, and ideally I'd like to avoid making our own. As a user of this project, how best would you see yourself configuring that? Would a setting in the main config be enough? Maybe allow that to be configurable via the toolbar?

**Comment by m1ga** [comment]
Ideally the `appc` tool should just fall back to a `ti` command so a user never has to think about which CLI command to use ;-) 

A normal config setting/toolbar switch should be enough. Something you normally won't do that often but it can be handy if you work on ti-only project. At the moment you can't use the deploy feature (I use it for emulators because it is quicker to select them there).

**Comment by ewanharris** [comment]
@m1ga ideally yes we would just "do the right thing", but given the ways this plugins relies on the tooling that isn't just building (completions creation/loading, alloy component generation, updates, environment information gathering etc.), we really need to know the what the preferred toolset is upfront.

I think we'll take an investigation into how we could do this, what the code would look like, and then go from there. I believe we're hoping to resolve the appc/ti split during the next year so dependent on the timelines of that I'd like to try avoid introducing the complexity of where our tooling situation lies today to the editor plugins :)

**Comment by m1ga** [comment]
https://github.com/appcelerator/atom-appcelerator-titanium/pull/367
A start :)

**Comment by ewanharris** [comment]
Released as 2.0.0, then an actual working build was put out in 2.0.1 🙂 

Thanks again @m1ga!
