### ISSUE TITLE
Appcelerator Not Finding JDK When Attempting to Run Android Emulator

### ISSUE THREAD

**Issue by Jlindsey00** [appcelerator/atom-appcelerator-titanium#268]
Hello, 

I am using Windows 10 and I recently tried to run an android emulator on Appcelerator and the below error keeps popping up:

_[ERROR] JDK (Java Development Kit) not found.
[ERROR] If you already have installed the JDK, verify your JAVA_HOME environment variable is correctly set.
[ERROR] The JDK can be downloaded and installed from http://appcelerator.com/jdk.
Build failed. Process exited with code 1.__

I have set my JAVA_HOME many times and bounced back and forth from a jdk and jre folder. No matter which path I set the same error returns. 

What help can you provide to fix this issue? 

Thank you

**Comment by ewanharris** [comment]
@Jlindsey00, sorry for the slow response here. On my Windows machine the `JAVA_HOME` environment variable is set to `C:\Program Files\Java\jdk1.8.0_221`. I think that link points to Java 14 which I don't think is fully supported yet, Java 8 or Java 11 should work ok.

To quickly test a path you could do the following, when you've got the right path it should report `No issues detected`
```
set JAVA_HOME=<PATH_TO_TEST>
appc ti info -t jdk
```
