### ISSUE TITLE
better icon for live view

### ISSUE THREAD

**Issue by testampat** [appcelerator/atom-appcelerator-titanium#306]
Current icon for live view is very confusing and you cannot identify whether it is on or off.
Can we get two distinct icons for live view on and off

**Comment by ewanharris** [comment]
We're limited here by what [Octicons](https://primer.style/octicons/) offers, I think rather than grey-ing out the eye we could probably switch over to `eye-slash` when liveview is disabled

**Comment by testampat** [comment]
what i observed is, if use one dark theme, icons can be differentiated easily. For other themes they are not that different

**Comment by ewanharris** [comment]
2.1.0 was just released with this change
