### ISSUE TITLE
Error executing 'appc login' command  

### ISSUE THREAD

**Issue by tsukoyumi** [appcelerator/atom-appcelerator-titanium#370]
To keep the issue tracker clean, we request that general questions go to the [#titanium_editors](https://ti-slack.slack.com/messages/C0FTDDNDS) channel.

Ensure you have installed Appcelerator CLI tools. You may need to set the full path to the appc command in package settings.
im having some trouble can someone help me what this means and how to fix it

**Comment by ewanharris** [comment]
@tsukoyumi Check out getting started guide [here](https://platform.axway.com/#/product/cli). It'll show you how to install the CLI
