### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by m1ga** [appcelerator/atom-appcelerator-titanium#62]
Currently not working on Linux but I'll do some more tests soon and try to fix them.

- [x]  build select & run is empty
- [x] platform list is empty
- [x] `options.args.join is not a function` in /lib/index.js:401 if you just click run (caused by above)

**Comment by chrisbowley** [comment]
Thanks for this! We focussed on macOS and Windows for the initial release. Any help much appreciated.

**Comment by m1ga** [comment]
Was just a missing `if`!
https://github.com/appcelerator/atom-appcelerator-titanium/pull/63
working fine now
