### ISSUE TITLE
Showing "Preparing..." message from last 20 minutes or over

### ISSUE THREAD

**Issue by prashantsaini1** [appcelerator/atom-appcelerator-titanium#65]
Hi team, I am trying to use your Atom package & I did a restart after installing it. But it's showing the *Preparing...* message from infinite time. I tried it on various projects, but this package is not working on my Atom.

See screenshot, just this "Preparing..." message & no drop-down, no button is working at all.

![screen shot 2017-12-10 at 12 38 39 am](https://user-images.githubusercontent.com/20779626/33798694-47d90778-dd43-11e7-85a8-e3771b94e9e4.png)

My Atom version is 1.22.1

**Comment by m1ga** [comment]
@prashantsaini1 you could open "View - Developer - Toogle Dev Tools" and check if there is an error in the log. Also try to restart the window with the dev tools open "View - Developer - Restart Window". Might give a clue what's wrong

**Comment by hansemannn** [comment]
@prashantsaini1 I'd recommend the same. Let us know.

**Comment by prashantsaini1** [comment]
Not sure about what happened as it is working today, but yesterday it didn't work for whole day.
