### ISSUE TITLE
Uncaught SyntaxError: Unexpected number in JSON at position 4

### ISSUE THREAD

**Issue by caspahouzer** [appcelerator/atom-appcelerator-titanium#67]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [appcelerator-titanium](https://github.com/appcelerator/atom-appcelerator-titanium) package 1.0.2

### Stack Trace

Uncaught SyntaxError: Unexpected number in JSON at position 4

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html:1

SyntaxError: Unexpected number in JSON at position 4
    at JSON.parse (<anonymous>)
    at exit (/packages/appcelerator-titanium/lib/appc.js:25:23)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:351:17
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
```

### Non-Core Packages

```
appcelerator-titanium 1.0.2 
build 0.69.0 
busy-signal 1.4.3 
jsdoc-generator 0.2.3 
tishadow 0.2.3 
titanium-build 0.8.1 
titanium-language-javascript 0.48.0 
```

**Comment by chrisbowley** [comment]
@caspahouzer do you have appc CLI installed? If so which version of appc and Titanium are you running? Do you get a valid output if you run `appc info -o json`?

**Comment by m1ga** [comment]
The appc command will output errors before the json. With node 7 you'll get this as a result
```Appcelerator Command-Line Interface
Copyright (c) 2014-2017, Appcelerator, Inc.  All Rights Reserved.

ERROR: appc requires Node.js >=8.0.0
Visit http://nodejs.org/ to download a newer version.
```
and then `JSON.parse` of course can't parse it. That also results in https://github.com/appcelerator/atom-appcelerator-titanium/issues/65

**Comment by caspahouzer** [comment]
That did the trick. Thank you

**Comment by Jei** [comment]
@caspahouzer How did you solve this problem? I'm having the same issue with:
node 8.9.3
appc 6.2.4
titanium CLI 5.0.14

The command `appc info -o json` fails with a similar error as the one in #68 and here:
`Unexpected token R in JSON at position 0`

**Comment by poledeveloper** [comment]
@caspahouzer I have the same issue of @Jei 
node v8.9.4
appc 7.0.2
titanium CLI 5.0.14

**Comment by m1ga** [comment]
@Jei what does `appc info` without the JSON output print out? It looks like there is an error that can't be parsed as a JSON

**Comment by Jei** [comment]
@m1ga It does. I also updated the Appcelerator CLI version to 7.0.2 just to be sure.
The complete output is:
```
╰─$ appc info                                                                                                                                                                                                                          
Appcelerator Command-Line Interface, version 7.0.2
Copyright (c) 2014-2018, Appcelerator, Inc.  All Rights Reserved.

An uncaught exception was thrown!
Unexpected token R in JSON at position 0
Unexpected token R in JSON at position 0
```

**Comment by m1ga** [comment]
Then it looks like an appc problem and not related to the plugin. The plugin just tries to parse the output and since the JSON is broken it won't work. But the real error is inside your CLI somewhere.
