### ISSUE TITLE
Line comments (Ctrl + /) not working in Alloy XML

### ISSUE THREAD

**Issue by m1ga** [appcelerator/atom-appcelerator-titanium#70]
When having the file type set to `Alloy (XML)` the Line comments (Ctrl + /) won't work me. Changing to `XML` and it works fine again.

Package version 1.0.2
Atom 1.23.0
Fedora Linux

Will check OSX tomorrow

**Comment by chrisbowley** [comment]
Confirmed this is also the case on macOS.

**Comment by hanih** [comment]
It's working for me

**Comment by celsoperezcruz** [comment]
Not working for me, I changed to xml and works!

**Comment by hansemannn** [comment]
Works here as well, using the latest version of Atom and the plugin. Closing for now!
