### ISSUE TITLE
Toolbar remains when closing project

### ISSUE THREAD

**Issue by focussing** [appcelerator/atom-appcelerator-titanium#76]
First of all THANK YOU for this great package. Now I can switch to Atom for all my development projects :)

One thing I noticed when closing a project, or switch to another via Project Manager, is that the toolbar at the top remains.

How can I close the toolbar also?

**Comment by chrisbowley** [comment]
Thanks @focussing :) As with #73, the package currently works with a single project per window. 1.0.3 addresses some issues with non-Titanium projects but I'll look at this behaviour too.

Thanks for creating https://jira.appcelerator.org/browse/ATOM-40, I'll close this issue and follow up there.

**Comment by focussing** [comment]
sorry @chrisbowley I saw the possibility for jira.appcelerator later... I put it here already...
