### ISSUE TITLE
Unique directory for builds

### ISSUE THREAD

**Issue by sandrolain** [appcelerator/atom-appcelerator-titanium#83]
Option to export builds into a single directory that is the same for all projects, rather than just the "dist" sub-directory of the project.

This could be a global parameter of the package, or as a selection of the destination directory at compile time.

**Comment by chrisbowley** [comment]
You can set the distribution output path in the package settings, this can be relative to the current project or an absolute path.

**Comment by sandrolain** [comment]
thank you, I did not understand that you could even specify an absolute path
