### ISSUE TITLE
Where is the build bar ?

### ISSUE THREAD

**Issue by ikalangita** [appcelerator/atom-appcelerator-titanium#84]
Hello,

Freshly installed the plugin, where can i see the build bar ? 

Thank you.

**Comment by chrisbowley** [comment]
The toolbar is displayed when you open a Titanium project.

**Comment by ikalangita** [comment]
Hi, thank you

Le mer. 31 janv. 2018 à 23:43, Chris Bowley <notifications@github.com> a
écrit :
