### ISSUE TITLE
Console is empty

### ISSUE THREAD

**Issue by ikalangita** [appcelerator/atom-appcelerator-titanium#86]
Hello,

I installed this atom plugin successfully and works great with ti shadow, i noticed a major bug that i cannot output any Ti.API.info or console.log to the console which is still empty, or i missed something ? thank you.

**Comment by chrisbowley** [comment]
The package pipes the output from the build process to the console so you need to execute the build from the package using the toolbar or keyboard shortcut. Building and running using TiShadow won't display output in the console.
