### ISSUE TITLE
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.

### ISSUE THREAD

**Issue by inaffect-ag** [appcelerator/atom-appcelerator-titanium#96]
can't run/deploy a project. no other error/log is given then that above.
with java 1.8.0, node v8.9.3.

**Comment by hansemannn** [comment]
This does not seem to be related to the Atom package. If it still occurs, please let the SDK team know via https://jira.appcelerator.org and you will get prompt feedback!

**Comment by SeanMaraj** [comment]
@inaffect-ag did you ever figure this out?
