### ISSUE TITLE
Feature: Take screenshot from device

### ISSUE THREAD

**Issue by m1ga** [appcelerator/atom-appcelerator-titanium#98]
On Android you can easily take a screenshot from an attached device with `adb exec-out screencap -p > screen.png`
That would make a useful button. 
Didn't find an easy command for iOS so it would be an Android only option I guess.

**Comment by Brianggalvez** [comment]
Maybe for ios we could use this:
 `xcrun simctl io booted screenshot`

**Comment by hansemannn** [comment]
Wondering how you distinguish between different sims on iOS, since Xcode 9+ allows multiple sims to be opened at the same time. If it can use the --device-id we have, it may solve it.

**Comment by m1ga** [comment]
A start for Android: https://github.com/appcelerator/atom-appcelerator-titanium/pull/112

**Comment by m1ga** [comment]
First implementation done in #112
